spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/bes2-db
    username : root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate

server:
  servlet:
    encoding:
      force-response: true
